create table if not exists public.categorias (
  id int8 generated by default as identity primary key,
  nombre text not null unique
);

create table if not exists public.productos (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  descripcion text not null default '',
  precio_original numeric(12, 2) not null check (precio_original >= 0),
  precio_oferta numeric(12, 2) check (precio_oferta is null or precio_oferta >= 0),
  stock_quantity int4 not null default 0 check (stock_quantity >= 0),
  imagenes jsonb not null default '[]'::jsonb,
  categoria_id int8 not null references public.categorias(id) on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.configuracion_sitio (
  clave text primary key,
  valor text not null
);

create table if not exists public.admin_users (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.pedidos (
  id uuid primary key default gen_random_uuid(),
  total numeric(12, 2) not null check (total >= 0),
  subtotal numeric(12, 2) not null default 0 check (subtotal >= 0),
  shipping_cost numeric(12, 2) not null default 0 check (shipping_cost >= 0),
  delivery_method text not null default 'retiro',
  payment_method text not null default 'tarjeta_demo',
  status_pago text not null default 'pendiente',
  items jsonb not null default '[]'::jsonb,
  customer_name text,
  customer_company text,
  customer_email text,
  customer_address text,
  created_at timestamptz not null default now()
);

alter table public.pedidos add column if not exists subtotal numeric(12, 2) not null default 0 check (subtotal >= 0);
alter table public.pedidos add column if not exists shipping_cost numeric(12, 2) not null default 0 check (shipping_cost >= 0);
alter table public.pedidos add column if not exists delivery_method text not null default 'retiro';
alter table public.pedidos add column if not exists payment_method text not null default 'tarjeta_demo';
alter table public.pedidos add column if not exists items jsonb not null default '[]'::jsonb;
alter table public.pedidos add column if not exists customer_name text;
alter table public.pedidos add column if not exists customer_company text;
alter table public.pedidos add column if not exists customer_email text;
alter table public.pedidos add column if not exists customer_address text;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select
    coalesce((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin', false)
    or exists (
      select 1
      from public.admin_users
      where lower(email) = lower(auth.email())
    );
$$;

alter table public.categorias enable row level security;
alter table public.productos enable row level security;
alter table public.configuracion_sitio enable row level security;
alter table public.pedidos enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Admins can read admin users" on public.admin_users;
create policy "Admins can read admin users"
on public.admin_users for select
using (public.is_admin());

drop policy if exists "Public can read categories" on public.categorias;
create policy "Public can read categories"
on public.categorias for select
using (true);

drop policy if exists "Admins can write categories" on public.categorias;
create policy "Admins can write categories"
on public.categorias for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read products" on public.productos;
create policy "Public can read products"
on public.productos for select
using (true);

drop policy if exists "Admins can write products" on public.productos;
create policy "Admins can write products"
on public.productos for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Public can read site config" on public.configuracion_sitio;
create policy "Public can read site config"
on public.configuracion_sitio for select
using (true);

drop policy if exists "Admins can write site config" on public.configuracion_sitio;
create policy "Admins can write site config"
on public.configuracion_sitio for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can read orders" on public.pedidos;
create policy "Admins can read orders"
on public.pedidos for select
using (public.is_admin());

drop policy if exists "Public can create orders" on public.pedidos;
create policy "Public can create orders"
on public.pedidos for insert
with check (true);

drop policy if exists "Admins can write orders" on public.pedidos;
drop policy if exists "Admins can update orders" on public.pedidos;
create policy "Admins can update orders"
on public.pedidos for update
using (public.is_admin())
with check (public.is_admin());

insert into public.categorias (nombre)
values ('Objetos'), ('Textiles'), ('Iluminacion')
on conflict (nombre) do nothing;

insert into public.configuracion_sitio (clave, valor)
values ('logo_url', '')
on conflict (clave) do nothing;

insert into public.configuracion_sitio (clave, valor)
values
  ('contact_heading', 'Contactanos cuando quieras'),
  ('contact_whatsapp', '+56 9 1234 5678'),
  ('contact_mail', 'hola@nomadeproject.cl'),
  ('social_heading', 'Siguenos en:'),
  ('social_instagram', 'https://instagram.com/nomadeproject'),
  ('social_facebook', 'https://facebook.com/nomadeproject'),
  ('about_title', 'Acerca de Nomade'),
  ('about_content', 'Nomade nace como una seleccion de objetos con oficio, materia y pausa. Cada pieza se elige para acompanar proyectos que buscan belleza cotidiana sin exceso.'),
  ('about_image', 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=85')
on conflict (clave) do nothing;

insert into storage.buckets (id, name, public)
values ('imagenes-productos', 'imagenes-productos', true),
       ('branding', 'branding', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read product images" on storage.objects;
create policy "Public can read product images"
on storage.objects for select
using (bucket_id in ('imagenes-productos', 'branding'));

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert
with check (bucket_id in ('imagenes-productos', 'branding') and public.is_admin());

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update
using (bucket_id in ('imagenes-productos', 'branding') and public.is_admin())
with check (bucket_id in ('imagenes-productos', 'branding') and public.is_admin());

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete
using (bucket_id in ('imagenes-productos', 'branding') and public.is_admin());
